## Using an Artificial Neural Network

Implemented first, with the original unbalanced dataset and then with  a balanced dataset

Here, 
balanced means whether the frequency of target values (here, 1 and 0) is equal or not 
(Equal prior probability)

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0'

### Data Preprocessing

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
dataset.shape

(10000, 14)

In [5]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

In [8]:
# Label Encoding the "Gender" column 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])  #gender column 

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [10]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Building the ANN

In [14]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [15]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [17]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Training the ANN

In [18]:
# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [19]:
# Training the ANN on Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 157us/sample - loss: 0.5550 - accuracy: 0.7681
Epoch 2/100
8000/8000 [==============================] - 1s 83us/sample - loss: 0.4671 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 138us/sample - loss: 0.4437 - accuracy: 0.7962
Epoch 4/100
8000/8000 [==============================] - 1s 147us/sample - loss: 0.4345 - accuracy: 0.7981
Epoch 5/100
8000/8000 [==============================] - 2s 196us/sample - loss: 0.4291 - accuracy: 0.8019
Epoch 6/100
8000/8000 [==============================] - 1s 122us/sample - loss: 0.4245 - accuracy: 0.8048
Epoch 7/100
8000/8000 [==============================] - 1s 122us/sample - loss: 0.4203 - accuracy: 0.8086
Epoch 8/100
8000/8000 [==============================] - 1s 103us/sample - loss: 0.4156 - accuracy: 0.8106
Epoch 9/100
8000/8000 [==============================] - 1s 83us/sample - loss: 0.4113 - accuracy: 0.8135
Epoch 10/100
8000

8000/8000 [==============================] - 0s 57us/sample - loss: 0.3559 - accuracy: 0.8510
Epoch 78/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3553 - accuracy: 0.8486
Epoch 79/100
8000/8000 [==============================] - 1s 75us/sample - loss: 0.3554 - accuracy: 0.8496
Epoch 80/100
8000/8000 [==============================] - 0s 61us/sample - loss: 0.3548 - accuracy: 0.8509
Epoch 81/100
8000/8000 [==============================] - 1s 85us/sample - loss: 0.3547 - accuracy: 0.8509
Epoch 82/100
8000/8000 [==============================] - 1s 87us/sample - loss: 0.3544 - accuracy: 0.8509
Epoch 83/100
8000/8000 [==============================] - 0s 56us/sample - loss: 0.3545 - accuracy: 0.8501
Epoch 84/100
8000/8000 [==============================] - 1s 63us/sample - loss: 0.3545 - accuracy: 0.8514
Epoch 85/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.3541 - accuracy: 0.8512
Epoch 86/100
8000/8000 [==========================

### Making the predictions and evaluating the model

In [20]:
# Predicting results for Test set
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


###  The Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1507   88]
 [ 212  193]]


0.85

In [22]:
test_loss, test_accuracy = ann.evaluate(X_test, y_test)

2000/2000 [==============================] - 0s 87us/sample - loss: 0.3561 - accuracy: 0.8500


In [23]:
print('\nTest loss: {0:.2f}. Test accuracy: {1:.2f}%'.format(test_loss, test_accuracy*100.))


Test loss: 0.36. Test accuracy: 85.00%


## Building an ANN now with a balanced dataset and early stopping for the ANN training 

In [24]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [25]:
#Data preprocessing
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [26]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [27]:
# Encoding categorical data
# Label Encoding the "Gender" column 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])  #gender column 

In [28]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

### Balancing dataset

In [29]:
#Balancing dataset

unscaled_inputs_all = X
targets_all = y


num_one_targets = int(np.sum(targets_all))
zero_targets_counter = 0
indices_to_remove = []

for i in range(targets_all.shape[0]):
    if targets_all[i] ==0:
        zero_targets_counter += 1
        if zero_targets_counter > num_one_targets:
            indices_to_remove.append(i)
        
unscaled_inputs_equal_priors = np.delete(unscaled_inputs_all, indices_to_remove, axis=0)
targets_equal_priors = np.delete(targets_all, indices_to_remove,axis=0)

### Shuffling the dataset

In [30]:
#shuffle dataset

shuffled_indices = np.arange(unscaled_inputs_equal_priors.shape[0])
np.random.shuffle(shuffled_indices)

shuffled_inputs = unscaled_inputs_equal_priors[shuffled_indices]
shuffled_targets = targets_equal_priors[shuffled_indices]

### Scaling inputs

In [31]:
from sklearn import preprocessing
X = preprocessing.scale(shuffled_inputs)
y = shuffled_targets

In [32]:
X.shape, y.shape

((4074, 12), (4074,))

In [33]:
X

array([[ 1.10023921, -0.67145715, -0.55712583, ...,  0.64807945,
         1.07975424,  0.05399694],
       [-0.90889326, -0.67145715,  1.79492664, ...,  0.64807945,
         1.07975424, -0.46926781],
       [-0.90889326, -0.67145715,  1.79492664, ..., -1.54302069,
        -0.92613667, -0.51757025],
       ...,
       [-0.90889326, -0.67145715,  1.79492664, ...,  0.64807945,
        -0.92613667,  1.48845067],
       [-0.90889326,  1.48929832, -0.55712583, ...,  0.64807945,
        -0.92613667,  1.14264484],
       [ 1.10023921, -0.67145715, -0.55712583, ...,  0.64807945,
         1.07975424,  1.19595601]])

### Splitting dataset into the Training set, Test set and Validation set

In [34]:
#Splitting into train, validation and test

samples_count = X.shape[0]

train_samples_count = int(0.8*samples_count)
validation_samples_count = int(0.1*samples_count)
test_samples_count = samples_count - train_samples_count - validation_samples_count


In [35]:
train_inputs = X[:train_samples_count]
train_targets = y[:train_samples_count]

validation_inputs = X[train_samples_count:train_samples_count+validation_samples_count]
validation_targets = y[train_samples_count:train_samples_count+validation_samples_count]

test_inputs = X[train_samples_count+validation_samples_count:]
test_targets = y[train_samples_count+validation_samples_count:]

### Building and training the ANN

In [36]:
input_size = 6
output_size = 1
hidden_layer_size = 6
    
model = tf.keras.Sequential([
    tf.keras.layers.Dense(hidden_layer_size, activation='relu'), # 1st hidden layer
    tf.keras.layers.Dense(hidden_layer_size, activation='relu'), # 2nd hidden layer
    tf.keras.layers.Dense(output_size, activation='sigmoid') # output layer
])


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

batch_size = 32
max_epochs = 100

# setting an early stopping mechanism
# let's set patience=2, to be a bit tolerant against random validation loss increases
early_stopping = tf.keras.callbacks.EarlyStopping(patience=2)

model.fit(train_inputs, 
          train_targets, 
          batch_size=batch_size, 
          epochs=max_epochs,
          callbacks=[early_stopping], 
          validation_data=(validation_inputs, validation_targets),
          verbose = 2 
          )  

Train on 3259 samples, validate on 407 samples
Epoch 1/100
3259/3259 - 1s - loss: 0.6769 - accuracy: 0.5683 - val_loss: 0.6620 - val_accuracy: 0.6265
Epoch 2/100
3259/3259 - 0s - loss: 0.6433 - accuracy: 0.6490 - val_loss: 0.6400 - val_accuracy: 0.6388
Epoch 3/100
3259/3259 - 0s - loss: 0.6178 - accuracy: 0.6729 - val_loss: 0.6265 - val_accuracy: 0.6437
Epoch 4/100
3259/3259 - 0s - loss: 0.6017 - accuracy: 0.6873 - val_loss: 0.6196 - val_accuracy: 0.6536
Epoch 5/100
3259/3259 - 0s - loss: 0.5921 - accuracy: 0.6953 - val_loss: 0.6157 - val_accuracy: 0.6536
Epoch 6/100
3259/3259 - 0s - loss: 0.5860 - accuracy: 0.7014 - val_loss: 0.6132 - val_accuracy: 0.6609
Epoch 7/100
3259/3259 - 0s - loss: 0.5819 - accuracy: 0.7064 - val_loss: 0.6108 - val_accuracy: 0.6683
Epoch 8/100
3259/3259 - 0s - loss: 0.5794 - accuracy: 0.7076 - val_loss: 0.6083 - val_accuracy: 0.6757
Epoch 9/100
3259/3259 - 0s - loss: 0.5773 - accuracy: 0.7094 - val_loss: 0.6068 - val_accuracy: 0.6757
Epoch 10/100
3259/3259 - 1

loss: 0.4440 - accuracy: 0.7849 - val_loss: 0.4492 - val_accuracy: 0.7985

### Testing and evaluating the model

In [37]:
test_loss, test_accuracy = model.evaluate(test_inputs, test_targets)

408/408 [==============================] - 0s 48us/sample - loss: 0.4403 - accuracy: 0.7721


In [38]:
print('\nTest loss: {0:.2f}. Test accuracy: {1:.2f}%'.format(test_loss, test_accuracy*100.))


Test loss: 0.44. Test accuracy: 77.21%
